env:
  FOO: bar

install: |
  # clear_cache: c28d0f6fd4e579c849d06b60c8e22351
  sudo apt update -y
  # sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends

setup: |
  echo $FOO

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    # - test_8_pool/*_test.sh
    - test_5_smoke/*_test.sh
    # - test_5_stress/*_test.sh
    # - test_17_stress/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
