[env]
FOO = "bar"

[base_image]
commands = '''
# clear_cache: af3ca715df2b8af2e591b53a0fdea8c7
sudo apt update -y
sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends
'''

[before_test_run]
commands = '''
echo SETUP
'''

[test_run.default]
env.FOO = "test suite bar"
env.BAZ = "quux"

command = "sh"
# files = ["test_5_smoke/*_test.sh"]
# files = ["test_5_long/*_test.sh"]
# files = ["test_5_stress/*_test.sh"]
# files = ["test_5_fail/*_test.sh"]
# files = ["test_8_pool_stress/*_test.sh"]
files = ["test_17_stress/*_test.sh"]
# files = ["test_17_mins/*_test.sh"]
# files = ["test_34_mins/*_test.sh"]
# files = ["test_68_mins/*_test.sh"]
# files = ["test_136_mins/*_test.sh"]
# files = ["test_272_mins/*_test.sh"]
