env:
  FOO: bar

install: |
  # clear_cache: a7e52558ed93a0314ea7211835b512ba
  sudo apt-get update -y
  sudo apt-get install make gcc g++ make -y --no-install-recommends

setup: |
  echo $FOO

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    # - test_8_pool/*_test.sh
    - test_5_smoke/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
