env:
  FOO: bar

install: |
  # clear_cache: 27b16c4eaef6dc5aa788d9166ca69817
  sudo apt update -y
  # sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends

setup: |
  echo $FOO

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    # - test_8_pool/*_test.sh
    - test_5_smoke/*_test.sh
    # - test_5_stress/*_test.sh
    # - test_17_stress/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
