env:
  FOO: bar

install: |
  # clear_cache: e70887a1c171df38c016d88b3b57c56f
  sudo apt update -y
  sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends

setup: |
  sudo apt update -y

  sudo apt install -y --no-install-recommends \
    autoconf bison build-essential curl g++ git libdb-dev libffi-dev \
    libgdbm-dev libncurses5-dev libreadline6-dev libssl-dev \
    libyaml-dev make libssl-dev libpq-dev \
    software-properties-common wget zlib1g-dev \
    cmake pkg-config postgresql-client

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    # - test_8_pool_stress/*_test.sh
    # - test_5_smoke/*_test.sh
    - test_5_stress/*_test.sh
    # - test_17_stress/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
