env.FOO = "bar"

setup.packages = """
# clear_cache: c1e5a655-37a9-4475-9fd4-75545369a121
sudo apt update -y
sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends
"""

setup.test_suite = """
echo SETUP
"""

[test_suite.default]
env.FOO = "test suite bar"
env.BAZ = "quux"

command = "sh"
files = ["test_5_smoke/*_test.sh"]
# files = ["test_5_long/*_test.sh"]
# files = ["test_5_stress/*_test.sh"]
# files = ["test_5_fail/*_test.sh"]
# files = ["test_8_pool_stress/*_test.sh"]
# files = ["test_17_stress/*_test.sh"]
# files = ["test_17_mins/*_test.sh"]
# files = ["test_34_mins/*_test.sh"]
# files = ["test_68_mins/*_test.sh"]
# files = ["test_136_mins/*_test.sh"]
# files = ["test_272_mins/*_test.sh"]
