env.FOO = "bar"

setup.packages = """
# clear_cache: b406265b-9393-43f0-b3dd-a33f06e6a127
sudo apt update -y
sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends
"""

setup.test_suite = """
echo SETUP
mkdir -p .cache ~/.cache
touch .cache/$( uuidgen ).txt ~/.cache/$( uuidgen ).txt
"""

setup.cache = [".cache", "~/.cache"]

[test_suite.default]
env.FOO = "test suite bar"
env.BAZ = "quux"

command = "sh"
files = ["test_5_smoke/*_test.sh"]
# files = ["test_5_long/*_test.sh"]
# files = ["test_5_stress/*_test.sh"]
# files = ["test_5_fail/*_test.sh"]
# files = ["test_8_pool_stress/*_test.sh"]
# files = ["test_17_stress/*_test.sh"]
# files = ["test_17_mins/*_test.sh"]
# files = ["test_34_mins/*_test.sh"]
# files = ["test_68_mins/*_test.sh"]
# files = ["test_136_mins/*_test.sh"]
# files = ["test_272_mins/*_test.sh"]
