env:
  FOO: bar

install: |
  # clear_cache: abc6273c6c44109d3e9bb0a83a12dd4b
  sudo apt update -y
  sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends

setup: |
  echo SETUP

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    # - test_8_pool_stress/*_test.sh
    - test_5_smoke/*_test.sh
    # - test_5_stress/*_test.sh
    # - test_5_fail/*_test.sh
    # - test_17_stress/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
