env:
  FOO: bar

install: |
  # clear_cache: 467b578432e6867fd08a232e44233eca
  sudo apt-get update -y
  sudo apt-get install make gcc g++ make -y --no-install-recommends

setup: |
  echo $FOO

test_suite:
  env:
    FOO: test suite bar
    BAZ: quux

  command: sh

  files:
    - test_8_pool/*_test.sh
    # - test_smoke/*_test.sh
    # - test_17_mins/*_test.sh
    # - test_34_mins/*_test.sh
    # - test_68_mins/*_test.sh
    # - test_136_mins/*_test.sh
    # - test_272_mins/*_test.sh
