[env]
FOO = "bar"

[base_image]
commands = '''
# clear_cache: 15a106cf-3f46-4cfa-a2d1-253825dbd1c2
sudo apt update -y
sudo apt install g++ build-essential stress stress-ng -y --no-install-recommends
'''

[before_test_run]
commands = '''
echo SETUP
rm -Rf ~/.cache_test ./.cache_test
# mkdir -p ~/.cache_test/$( uuidgen )/foo.txt ./.cache_test/$( uuidgen )/foo.txt
ls -lahR ~/.cache_test .cache_test
'''

[cache]
directories = [ "~/.cache_test", ".cache_test" ]

[test_run.default]
env.FOO = "test suite bar"
env.BAZ = "quux"

command = "sh"
files = ["test_5_smoke/*_test.sh"]
# files = ["test_5_long/*_test.sh"]
# files = ["test_5_stress/*_test.sh"]
# files = ["test_5_fail/*_test.sh"]
# files = ["test_8_pool_stress/*_test.sh"]
# files = ["test_17_stress/*_test.sh"]
# files = ["test_17_mins/*_test.sh"]
# files = ["test_34_mins/*_test.sh"]
# files = ["test_68_mins/*_test.sh"]
# files = ["test_136_mins/*_test.sh"]
# files = ["test_272_mins/*_test.sh"]
